# Generated by Django 2.0.1 on 2018-01-26 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20180126_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodel',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
